"""Build Prism's x86_64 JNI glue (native/prism_jni) for the user's Horizon OS build.

Reads Horizon's framework jars from work/fs to find every native method Meta added (compared with
stock work/baseline/fs) and which library each class loads, generates the stub table, and compiles
it with the HLE sources (natives Prism implements, see native/prism_jni/prism_hle.h) into:

  work/build/jni/libprism_jni.so   preloaded into zygote
  work/build/jni/lib<name>.so      stand-ins for Meta's arm64 JNI libraries

    python tools/jni/build.py [--ndk PATH]
"""
import argparse
import glob
import json
import os
import re
import subprocess
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, 'tools', 'inventory'))
sys.path.insert(0, os.path.join(ROOT, 'tools', 'ota'))
import dex  # noqa: E402
from inventory import Tree, classpaths  # noqa: E402

SOURCE_DIR = os.path.join(ROOT, 'native', 'prism_jni')  # prism_jni.c and the HLE sources (hle_*.c)
API = 34


def find_ndk(sdk_hint):
    roots = [sdk_hint] if sdk_hint else []
    roots += [os.environ.get('ANDROID_NDK_HOME'), os.environ.get('ANDROID_NDK_ROOT')]
    for sdk in (os.environ.get('ANDROID_SDK_ROOT'), os.environ.get('ANDROID_HOME'),
                os.path.join(os.environ.get('LOCALAPPDATA', ''), 'Android', 'Sdk'), os.path.expanduser('~/Android/Sdk')):
        if sdk:
            roots += sorted(glob.glob(os.path.join(sdk, 'ndk', '*')), reverse=True)
    for root in roots:
        if root and os.path.isdir(os.path.join(root, 'toolchains', 'llvm')):
            return root
    sys.exit('Android NDK not found; pass --ndk')


def jar_dexes(path):
    with zipfile.ZipFile(path) as z:
        return [dex.Dex(z.read(n)) for n in sorted(z.namelist()) if re.fullmatch(r'classes\d*\.dex', n)]


def collect(horizon, baseline):
    """Returns (entries, stub libraries). An entry is (class, name, sig, lib, boot)."""
    cps = classpaths(horizon)
    boot = set(cps.get('BOOTCLASSPATH', []))
    server = set(cps.get('SYSTEMSERVERCLASSPATH', []))
    jars = sorted(j for j in boot | server if not j.startswith('/apex/'))
    stock_libs = {os.path.basename(p)[3:-3] for p in baseline.paths if re.search(r'/lib64/lib[^/]+\.so$', p)}
    entries, libs = {}, set()
    for jar in jars:
        h = jar_dexes(horizon.host(jar))
        b_path = baseline.host(jar)
        stock = {s for d in jar_dexes(b_path) for s in d.native_methods()} if os.path.exists(b_path) else set()
        loads = {}
        for d in h:
            for cls, lib in d.load_library_calls():
                loads.setdefault(cls, lib)
        for d in h:
            for signature in d.native_methods():
                if signature in stock:
                    continue
                cls, rest = signature.split('->')
                name, sig = rest.split('(', 1)
                lib = loads.get(cls, '')
                if lib in stock_libs:
                    lib = ''  # a stock library registers this class; libprism_jni adds Meta's natives then
                if lib:
                    libs.add(lib)
                entries[signature] = (cls[1:-1], name, '(' + sig, lib, jar in boot)
    return sorted(entries.values()), sorted(libs)


def c_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def generate(entries, path):
    lines = ['// Generated by tools/jni/build.py from the user\'s Horizon OS build. Do not edit.', '']
    for i, (_cls, _name, sig, _lib, _boot) in enumerate(entries):
        ret = sig[sig.index(')') + 1:]
        if ret in ('F', 'D'):
            lines.append(f'static jdouble stub_{i}(JNIEnv *e, jobject o) {{ (void)e, (void)o; prism_stub_hit({i}); return 0; }}')
        else:
            lines.append(f'static jlong stub_{i}(JNIEnv *e, jobject o) {{ (void)e, (void)o; prism_stub_hit({i}); return 0; }}')
    lines += ['', 'static const PrismNative kNatives[] = {']
    for i, (cls, name, sig, lib, boot) in enumerate(entries):
        lines.append(f'  {{{c_string(cls)}, {c_string(name)}, {c_string(sig)}, {c_string(lib)}, {int(boot)}, '
                     f'(void *)stub_{i}}},')
    lines += ['};', f'static const int kNativeCount = {len(entries)};', '']
    with open(path, 'w', newline='\n') as f:
        f.write('\n'.join(lines))


def compile_lib(ndk, out, include_dir, soname, defines):
    host = 'windows-x86_64' if os.name == 'nt' else 'linux-x86_64'
    clang = os.path.join(ndk, 'toolchains', 'llvm', 'prebuilt', host, 'bin', 'clang' + ('.exe' if os.name == 'nt' else ''))
    command = [clang, f'--target=x86_64-linux-android{API}', '-shared', '-fPIC', '-O2', '-std=c11', '-Wall',
               '-Wno-unused-function', f'-I{include_dir}', *defines,
               *sorted(glob.glob(os.path.join(SOURCE_DIR, '*.c'))), '-o', out,
               f'-Wl,-soname,{soname}', '-llog', '-lm', '-landroid', '-Wl,--build-id=sha1']
    subprocess.run(command, check=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--fs', default=os.path.join('work', 'fs'))
    ap.add_argument('--baseline', default=os.path.join('work', 'baseline', 'fs'))
    ap.add_argument('--out', default=os.path.join('work', 'build', 'jni'))
    ap.add_argument('--ndk')
    args = ap.parse_args()
    ndk = find_ndk(args.ndk)
    os.makedirs(args.out, exist_ok=True)
    entries, libs = collect(Tree(args.fs), Tree(args.baseline))
    generate(entries, os.path.join(args.out, 'prism_natives.inc'))
    print(f'{len(entries)} Meta natives ({sum(e[4] for e in entries)} on the boot classpath), '
          f'{len(libs)} stand-in libraries: {", ".join(libs)}')
    compile_lib(ndk, os.path.join(args.out, 'libprism_jni.so'), args.out, 'libprism_jni.so', [])
    for lib in libs:
        compile_lib(ndk, os.path.join(args.out, f'lib{lib}.so'), args.out, f'lib{lib}.so',
                    [f'-DPRISM_STUB_LIB={c_string(lib)}'])
    with open(os.path.join(args.out, 'libs.json'), 'w') as f:
        json.dump({'preload': 'libprism_jni.so', 'stand_ins': [f'lib{l}.so' for l in libs]}, f, indent=1)
    print(f'built {1 + len(libs)} libraries in {args.out}')


if __name__ == '__main__':
    main()
